#ifndef MESSAGE_H_INCLUDED
#define MESSAGE_H_INCLUDED

#include <sys/types.h>
#include <pthread.h>

/**
 * @brief Holds all elements of a message.
 */
typedef struct {
    /**
     * @brief Sequential number of request (generated by Un).
     */
    int i;
    /**
     * @brief Process ID (PID of client, if a request; PID of server, if an answer).
     */
    pid_t pid;
    /**
     * @brief ID of thread (client thread, if a request; server thread, if an answer).
     */
    pthread_t tid;
    /**
     * @brief Duration, in milliseconds, of usage of a place in a
     * bathroom (issued in the request, repeated in the answer if
     * there is an occupation; if occupation does not happen because the
     * bathroom is about to close, the server answers with -1).
     */
    int dur;
    /**
     * @brief Number of the place eventually issued in the bathroom
     * (this field is set with -1 in the request, and the answer will
     * set it to the appropriate value or -1 if occupation is unsuccessful
     * because the bathroom is about to close).
     */
    int pl;
} message_t;

#endif //MESSAGE_H_INCLUDED
